name: short
description: A URL shortener
author: wesleytodd
branding:
  icon: link
  color: green
inputs:
  token:
    description: The github token
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
